-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gcd]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Gcd.Types
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
open gcd

/- [core::num::{u8}::trailing_zeros]:
   Source: '/rustc/library/core/src/num/uint_macros.rs', lines 152:8-152:48
   Name pattern: [core::num::{u8}::trailing_zeros] -/
def core.num.U8.trailing_zeros : U8 → Result U32 := sorry

/- [core::num::{u16}::trailing_zeros]:
   Source: '/rustc/library/core/src/num/uint_macros.rs', lines 152:8-152:48
   Name pattern: [core::num::{u16}::trailing_zeros] -/
def core.num.U16.trailing_zeros : U16 → Result U32 := sorry

/- [core::num::{u32}::trailing_zeros]:
   Source: '/rustc/library/core/src/num/uint_macros.rs', lines 152:8-152:48
   Name pattern: [core::num::{u32}::trailing_zeros] -/
def core.num.U32.trailing_zeros : U32 → Result U32 := sorry

/- [core::num::{u64}::trailing_zeros]:
   Source: '/rustc/library/core/src/num/uint_macros.rs', lines 152:8-152:48
   Name pattern: [core::num::{u64}::trailing_zeros] -/
def core.num.U64.trailing_zeros : U64 → Result U32 := sorry

/- [core::num::{u128}::trailing_zeros]:
   Source: '/rustc/library/core/src/num/uint_macros.rs', lines 152:8-152:48
   Name pattern: [core::num::{u128}::trailing_zeros] -/
def core.num.U128.trailing_zeros : U128 → Result U32 := sorry

/- [core::num::{usize}::trailing_zeros]:
   Source: '/rustc/library/core/src/num/uint_macros.rs', lines 152:8-152:48
   Name pattern: [core::num::{usize}::trailing_zeros] -/
def core.num.Usize.trailing_zeros : Usize → Result U32 := sorry
