-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gcd]: function definitions
import Aeneas
import Gcd.Types
import Gcd.FunsExternal
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace gcd

/- [gcd::binary_u8]: loop 0:
   Source: 'src/lib.rs', lines 45:12-59:13 -/
def binary_u8_loop (u : U8) (v : U8) : Result U8 :=
  do
  let i ← core.num.U8.trailing_zeros v
  let v1 ← v >>> i
  let (u1, v2) ← if u > v1
                   then ok (v1, u)
                   else ok (u, v1)
  let v3 ← v2 - u1
  if v3 = 0#u8
  then ok u1
  else binary_u8_loop u1 v3
partial_fixpoint

/- [gcd::binary_u8]:
   Source: 'src/lib.rs', lines 35:8-62:9 -/
def binary_u8 (u : U8) (v : U8) : Result U8 :=
  if u = 0#u8
  then ok v
  else
    if v = 0#u8
    then ok u
    else
      do
      let i ← (↑(u ||| v) : Result U8)
      let shift ← core.num.U8.trailing_zeros i
      let u1 ← u >>> shift
      let v1 ← v >>> shift
      let i1 ← core.num.U8.trailing_zeros u1
      let u2 ← u1 >>> i1
      let u3 ← binary_u8_loop u2 v1
      u3 <<< shift

/- [gcd::euclid_u8]: loop 0:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u8_loop (a : U8) (b : U8) : Result U8 :=
  if b != 0#u8
  then do
       let b1 ← a % b
       euclid_u8_loop b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u8]:
   Source: 'src/lib.rs', lines 65:8-85:9 -/
def euclid_u8 (a : U8) (b : U8) : Result U8 :=
  do
  let (a1, b1) ← if a > b
                   then ok (a, b)
                   else ok (b, a)
  euclid_u8_loop a1 b1

end gcd
