-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gcd]: function definitions
import Aeneas
import Gcd.Types
import Gcd.FunsExternal
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace gcd

/- [gcd::binary_u8]: loop 0:
   Source: 'src/lib.rs', lines 45:12-59:13 -/
def binary_u8_loop (u : U8) (v : U8) : Result U8 :=
  do
  let i ← core.num.U8.trailing_zeros v
  let v1 ← v >>> i
  if u > v1
  then do
       let v2 ← u - v1
       if v2 = 0#u8
       then ok v1
       else binary_u8_loop v1 v2
  else do
       let v2 ← v1 - u
       if v2 = 0#u8
       then ok u
       else binary_u8_loop u v2
partial_fixpoint

/- [gcd::binary_u8]:
   Source: 'src/lib.rs', lines 35:8-62:9 -/
def binary_u8 (u : U8) (v : U8) : Result U8 :=
  if u = 0#u8
  then ok v
  else
    if v = 0#u8
    then ok u
    else
      do
      let i ← (↑(u ||| v) : Result U8)
      let shift ← core.num.U8.trailing_zeros i
      let u1 ← u >>> shift
      let v1 ← v >>> shift
      let i1 ← core.num.U8.trailing_zeros u1
      let u2 ← u1 >>> i1
      let u3 ← binary_u8_loop u2 v1
      u3 <<< shift

/- [gcd::binary_u16]: loop 0:
   Source: 'src/lib.rs', lines 45:12-59:13 -/
def binary_u16_loop (u : U16) (v : U16) : Result U16 :=
  do
  let i ← core.num.U16.trailing_zeros v
  let v1 ← v >>> i
  if u > v1
  then do
       let v2 ← u - v1
       if v2 = 0#u16
       then ok v1
       else binary_u16_loop v1 v2
  else do
       let v2 ← v1 - u
       if v2 = 0#u16
       then ok u
       else binary_u16_loop u v2
partial_fixpoint

/- [gcd::binary_u16]:
   Source: 'src/lib.rs', lines 35:8-62:9 -/
def binary_u16 (u : U16) (v : U16) : Result U16 :=
  if u = 0#u16
  then ok v
  else
    if v = 0#u16
    then ok u
    else
      do
      let i ← (↑(u ||| v) : Result U16)
      let shift ← core.num.U16.trailing_zeros i
      let u1 ← u >>> shift
      let v1 ← v >>> shift
      let i1 ← core.num.U16.trailing_zeros u1
      let u2 ← u1 >>> i1
      let u3 ← binary_u16_loop u2 v1
      u3 <<< shift

/- [gcd::binary_u32]: loop 0:
   Source: 'src/lib.rs', lines 45:12-59:13 -/
def binary_u32_loop (u : U32) (v : U32) : Result U32 :=
  do
  let i ← core.num.U32.trailing_zeros v
  let v1 ← v >>> i
  if u > v1
  then do
       let v2 ← u - v1
       if v2 = 0#u32
       then ok v1
       else binary_u32_loop v1 v2
  else do
       let v2 ← v1 - u
       if v2 = 0#u32
       then ok u
       else binary_u32_loop u v2
partial_fixpoint

/- [gcd::binary_u32]:
   Source: 'src/lib.rs', lines 35:8-62:9 -/
def binary_u32 (u : U32) (v : U32) : Result U32 :=
  if u = 0#u32
  then ok v
  else
    if v = 0#u32
    then ok u
    else
      do
      let i ← (↑(u ||| v) : Result U32)
      let shift ← core.num.U32.trailing_zeros i
      let u1 ← u >>> shift
      let v1 ← v >>> shift
      let i1 ← core.num.U32.trailing_zeros u1
      let u2 ← u1 >>> i1
      let u3 ← binary_u32_loop u2 v1
      u3 <<< shift

/- [gcd::binary_u64]: loop 0:
   Source: 'src/lib.rs', lines 45:12-59:13 -/
def binary_u64_loop (u : U64) (v : U64) : Result U64 :=
  do
  let i ← core.num.U64.trailing_zeros v
  let v1 ← v >>> i
  if u > v1
  then do
       let v2 ← u - v1
       if v2 = 0#u64
       then ok v1
       else binary_u64_loop v1 v2
  else do
       let v2 ← v1 - u
       if v2 = 0#u64
       then ok u
       else binary_u64_loop u v2
partial_fixpoint

/- [gcd::binary_u64]:
   Source: 'src/lib.rs', lines 35:8-62:9 -/
def binary_u64 (u : U64) (v : U64) : Result U64 :=
  if u = 0#u64
  then ok v
  else
    if v = 0#u64
    then ok u
    else
      do
      let i ← (↑(u ||| v) : Result U64)
      let shift ← core.num.U64.trailing_zeros i
      let u1 ← u >>> shift
      let v1 ← v >>> shift
      let i1 ← core.num.U64.trailing_zeros u1
      let u2 ← u1 >>> i1
      let u3 ← binary_u64_loop u2 v1
      u3 <<< shift

/- [gcd::binary_u128]: loop 0:
   Source: 'src/lib.rs', lines 45:12-59:13 -/
def binary_u128_loop (u : U128) (v : U128) : Result U128 :=
  do
  let i ← core.num.U128.trailing_zeros v
  let v1 ← v >>> i
  if u > v1
  then
    do
    let v2 ← u - v1
    if v2 = 0#u128
    then ok v1
    else binary_u128_loop v1 v2
  else do
       let v2 ← v1 - u
       if v2 = 0#u128
       then ok u
       else binary_u128_loop u v2
partial_fixpoint

/- [gcd::binary_u128]:
   Source: 'src/lib.rs', lines 35:8-62:9 -/
def binary_u128 (u : U128) (v : U128) : Result U128 :=
  if u = 0#u128
  then ok v
  else
    if v = 0#u128
    then ok u
    else
      do
      let i ← (↑(u ||| v) : Result U128)
      let shift ← core.num.U128.trailing_zeros i
      let u1 ← u >>> shift
      let v1 ← v >>> shift
      let i1 ← core.num.U128.trailing_zeros u1
      let u2 ← u1 >>> i1
      let u3 ← binary_u128_loop u2 v1
      u3 <<< shift

/- [gcd::binary_usize]: loop 0:
   Source: 'src/lib.rs', lines 45:12-59:13 -/
def binary_usize_loop (u : Usize) (v : Usize) : Result Usize :=
  do
  let i ← core.num.Usize.trailing_zeros v
  let v1 ← v >>> i
  if u > v1
  then
    do
    let v2 ← u - v1
    if v2 = 0#usize
    then ok v1
    else binary_usize_loop v1 v2
  else
    do
    let v2 ← v1 - u
    if v2 = 0#usize
    then ok u
    else binary_usize_loop u v2
partial_fixpoint

/- [gcd::binary_usize]:
   Source: 'src/lib.rs', lines 35:8-62:9 -/
def binary_usize (u : Usize) (v : Usize) : Result Usize :=
  if u = 0#usize
  then ok v
  else
    if v = 0#usize
    then ok u
    else
      do
      let i ← (↑(u ||| v) : Result Usize)
      let shift ← core.num.Usize.trailing_zeros i
      let u1 ← u >>> shift
      let v1 ← v >>> shift
      let i1 ← core.num.Usize.trailing_zeros u1
      let u2 ← u1 >>> i1
      let u3 ← binary_usize_loop u2 v1
      u3 <<< shift

/- [gcd::euclid_u8]: loop 0:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u8_loop0 (a : U8) (b : U8) : Result U8 :=
  if b != 0#u8
  then do
       let b1 ← a % b
       euclid_u8_loop0 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u8]: loop 1:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u8_loop1 (a : U8) (b : U8) : Result U8 :=
  if b != 0#u8
  then do
       let b1 ← a % b
       euclid_u8_loop1 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u8]:
   Source: 'src/lib.rs', lines 65:8-85:9 -/
def euclid_u8 (a : U8) (b : U8) : Result U8 :=
  if a > b
  then euclid_u8_loop0 a b
  else euclid_u8_loop1 b a

/- [gcd::euclid_u16]: loop 0:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u16_loop0 (a : U16) (b : U16) : Result U16 :=
  if b != 0#u16
  then do
       let b1 ← a % b
       euclid_u16_loop0 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u16]: loop 1:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u16_loop1 (a : U16) (b : U16) : Result U16 :=
  if b != 0#u16
  then do
       let b1 ← a % b
       euclid_u16_loop1 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u16]:
   Source: 'src/lib.rs', lines 65:8-85:9 -/
def euclid_u16 (a : U16) (b : U16) : Result U16 :=
  if a > b
  then euclid_u16_loop0 a b
  else euclid_u16_loop1 b a

/- [gcd::euclid_u32]: loop 0:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u32_loop0 (a : U32) (b : U32) : Result U32 :=
  if b != 0#u32
  then do
       let b1 ← a % b
       euclid_u32_loop0 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u32]: loop 1:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u32_loop1 (a : U32) (b : U32) : Result U32 :=
  if b != 0#u32
  then do
       let b1 ← a % b
       euclid_u32_loop1 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u32]:
   Source: 'src/lib.rs', lines 65:8-85:9 -/
def euclid_u32 (a : U32) (b : U32) : Result U32 :=
  if a > b
  then euclid_u32_loop0 a b
  else euclid_u32_loop1 b a

/- [gcd::euclid_u64]: loop 0:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u64_loop0 (a : U64) (b : U64) : Result U64 :=
  if b != 0#u64
  then do
       let b1 ← a % b
       euclid_u64_loop0 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u64]: loop 1:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u64_loop1 (a : U64) (b : U64) : Result U64 :=
  if b != 0#u64
  then do
       let b1 ← a % b
       euclid_u64_loop1 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u64]:
   Source: 'src/lib.rs', lines 65:8-85:9 -/
def euclid_u64 (a : U64) (b : U64) : Result U64 :=
  if a > b
  then euclid_u64_loop0 a b
  else euclid_u64_loop1 b a

/- [gcd::euclid_u128]: loop 0:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u128_loop0 (a : U128) (b : U128) : Result U128 :=
  if b != 0#u128
  then do
       let b1 ← a % b
       euclid_u128_loop0 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u128]: loop 1:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_u128_loop1 (a : U128) (b : U128) : Result U128 :=
  if b != 0#u128
  then do
       let b1 ← a % b
       euclid_u128_loop1 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u128]:
   Source: 'src/lib.rs', lines 65:8-85:9 -/
def euclid_u128 (a : U128) (b : U128) : Result U128 :=
  if a > b
  then euclid_u128_loop0 a b
  else euclid_u128_loop1 b a

/- [gcd::euclid_usize]: loop 0:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_usize_loop0 (a : Usize) (b : Usize) : Result Usize :=
  if b != 0#usize
  then do
       let b1 ← a % b
       euclid_usize_loop0 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_usize]: loop 1:
   Source: 'src/lib.rs', lines 75:12-82:13 -/
def euclid_usize_loop1 (a : Usize) (b : Usize) : Result Usize :=
  if b != 0#usize
  then do
       let b1 ← a % b
       euclid_usize_loop1 b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_usize]:
   Source: 'src/lib.rs', lines 65:8-85:9 -/
def euclid_usize (a : Usize) (b : Usize) : Result Usize :=
  if a > b
  then euclid_usize_loop0 a b
  else euclid_usize_loop1 b a

/- [gcd::{gcd::Gcd for u8}::gcd_binary]:
   Source: 'src/lib.rs', lines 94:12-96:13 -/
def GcdU8.gcd_binary (self : U8) (v : U8) : Result U8 :=
  binary_u8 self v

/- [gcd::{gcd::Gcd for u8}::gcd_]:
   Source: 'src/lib.rs', lines 89:12-91:13 -/
def GcdU8.gcd_ (self : U8) (other : U8) : Result U8 :=
  GcdU8.gcd_binary self other

/- [gcd::{gcd::Gcd for u8}::gcd_euclid]:
   Source: 'src/lib.rs', lines 99:12-101:13 -/
def GcdU8.gcd_euclid (self : U8) (other : U8) : Result U8 :=
  euclid_u8 self other

/- Trait implementation: [gcd::{gcd::Gcd for u8}]
   Source: 'src/lib.rs', lines 87:8-102:9 -/
@[reducible]
def GcdU8 : Gcd U8 := {
  gcd_ := GcdU8.gcd_
  gcd_binary := GcdU8.gcd_binary
  gcd_euclid := GcdU8.gcd_euclid
}

/- [gcd::{gcd::Gcd for u16}::gcd_binary]:
   Source: 'src/lib.rs', lines 94:12-96:13 -/
def GcdU16.gcd_binary (self : U16) (v : U16) : Result U16 :=
  binary_u16 self v

/- [gcd::{gcd::Gcd for u16}::gcd_]:
   Source: 'src/lib.rs', lines 89:12-91:13 -/
def GcdU16.gcd_ (self : U16) (other : U16) : Result U16 :=
  GcdU16.gcd_binary self other

/- [gcd::{gcd::Gcd for u16}::gcd_euclid]:
   Source: 'src/lib.rs', lines 99:12-101:13 -/
def GcdU16.gcd_euclid (self : U16) (other : U16) : Result U16 :=
  euclid_u16 self other

/- Trait implementation: [gcd::{gcd::Gcd for u16}]
   Source: 'src/lib.rs', lines 87:8-102:9 -/
@[reducible]
def GcdU16 : Gcd U16 := {
  gcd_ := GcdU16.gcd_
  gcd_binary := GcdU16.gcd_binary
  gcd_euclid := GcdU16.gcd_euclid
}

/- [gcd::{gcd::Gcd for u32}::gcd_binary]:
   Source: 'src/lib.rs', lines 94:12-96:13 -/
def GcdU32.gcd_binary (self : U32) (v : U32) : Result U32 :=
  binary_u32 self v

/- [gcd::{gcd::Gcd for u32}::gcd_]:
   Source: 'src/lib.rs', lines 89:12-91:13 -/
def GcdU32.gcd_ (self : U32) (other : U32) : Result U32 :=
  GcdU32.gcd_binary self other

/- [gcd::{gcd::Gcd for u32}::gcd_euclid]:
   Source: 'src/lib.rs', lines 99:12-101:13 -/
def GcdU32.gcd_euclid (self : U32) (other : U32) : Result U32 :=
  euclid_u32 self other

/- Trait implementation: [gcd::{gcd::Gcd for u32}]
   Source: 'src/lib.rs', lines 87:8-102:9 -/
@[reducible]
def GcdU32 : Gcd U32 := {
  gcd_ := GcdU32.gcd_
  gcd_binary := GcdU32.gcd_binary
  gcd_euclid := GcdU32.gcd_euclid
}

/- [gcd::{gcd::Gcd for u64}::gcd_binary]:
   Source: 'src/lib.rs', lines 94:12-96:13 -/
def GcdU64.gcd_binary (self : U64) (v : U64) : Result U64 :=
  binary_u64 self v

/- [gcd::{gcd::Gcd for u64}::gcd_]:
   Source: 'src/lib.rs', lines 89:12-91:13 -/
def GcdU64.gcd_ (self : U64) (other : U64) : Result U64 :=
  GcdU64.gcd_binary self other

/- [gcd::{gcd::Gcd for u64}::gcd_euclid]:
   Source: 'src/lib.rs', lines 99:12-101:13 -/
def GcdU64.gcd_euclid (self : U64) (other : U64) : Result U64 :=
  euclid_u64 self other

/- Trait implementation: [gcd::{gcd::Gcd for u64}]
   Source: 'src/lib.rs', lines 87:8-102:9 -/
@[reducible]
def GcdU64 : Gcd U64 := {
  gcd_ := GcdU64.gcd_
  gcd_binary := GcdU64.gcd_binary
  gcd_euclid := GcdU64.gcd_euclid
}

/- [gcd::{gcd::Gcd for u128}::gcd_binary]:
   Source: 'src/lib.rs', lines 94:12-96:13 -/
def GcdU128.gcd_binary (self : U128) (v : U128) : Result U128 :=
  binary_u128 self v

/- [gcd::{gcd::Gcd for u128}::gcd_]:
   Source: 'src/lib.rs', lines 89:12-91:13 -/
def GcdU128.gcd_ (self : U128) (other : U128) : Result U128 :=
  GcdU128.gcd_binary self other

/- [gcd::{gcd::Gcd for u128}::gcd_euclid]:
   Source: 'src/lib.rs', lines 99:12-101:13 -/
def GcdU128.gcd_euclid (self : U128) (other : U128) : Result U128 :=
  euclid_u128 self other

/- Trait implementation: [gcd::{gcd::Gcd for u128}]
   Source: 'src/lib.rs', lines 87:8-102:9 -/
@[reducible]
def GcdU128 : Gcd U128 := {
  gcd_ := GcdU128.gcd_
  gcd_binary := GcdU128.gcd_binary
  gcd_euclid := GcdU128.gcd_euclid
}

/- [gcd::{gcd::Gcd for usize}::gcd_binary]:
   Source: 'src/lib.rs', lines 94:12-96:13 -/
def GcdUsize.gcd_binary (self : Usize) (v : Usize) : Result Usize :=
  binary_usize self v

/- [gcd::{gcd::Gcd for usize}::gcd_]:
   Source: 'src/lib.rs', lines 89:12-91:13 -/
def GcdUsize.gcd_ (self : Usize) (other : Usize) : Result Usize :=
  GcdUsize.gcd_binary self other

/- [gcd::{gcd::Gcd for usize}::gcd_euclid]:
   Source: 'src/lib.rs', lines 99:12-101:13 -/
def GcdUsize.gcd_euclid (self : Usize) (other : Usize) : Result Usize :=
  euclid_usize self other

/- Trait implementation: [gcd::{gcd::Gcd for usize}]
   Source: 'src/lib.rs', lines 87:8-102:9 -/
@[reducible]
def GcdUsize : Gcd Usize := {
  gcd_ := GcdUsize.gcd_
  gcd_binary := GcdUsize.gcd_binary
  gcd_euclid := GcdUsize.gcd_euclid
}

end gcd
