-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gcd]: type definitions
import Aeneas
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace gcd

end gcd
