-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [gcd]: function definitions
import Aeneas
import Gcd.Types
import Gcd.FunsExternal
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace gcd

/- [gcd::binary_u8]: loop 0:
   Source: 'src/lib.rs', lines 47:12-59:13 -/
def binary_u8_loop (u : U8) (v : U8) : Result U8 :=
  if u != v
  then
    do
    let (u1, v1) ← if u > v
                     then ok (v, u)
                     else ok (u, v)
    let v2 ← v1 - u1
    let i ← core.num.U8.trailing_zeros v2
    let v3 ← v2 >>> i
    binary_u8_loop u1 v3
  else ok u
partial_fixpoint

/- [gcd::binary_u8]:
   Source: 'src/lib.rs', lines 36:8-62:9 -/
def binary_u8 (u : U8) (v : U8) : Result U8 :=
  if u = 0#u8
  then ok v
  else
    if v = 0#u8
    then ok u
    else
      do
      let i ← (↑(u ||| v) : Result U8)
      let shift ← core.num.U8.trailing_zeros i
      let u1 ← u >>> shift
      let v1 ← v >>> shift
      let i1 ← core.num.U8.trailing_zeros u1
      let u2 ← u1 >>> i1
      let i2 ← core.num.U8.trailing_zeros v1
      let v2 ← v1 >>> i2
      let u3 ← binary_u8_loop u2 v2
      u3 <<< shift

/- [gcd::euclid_u8]: loop 0:
   Source: 'src/lib.rs', lines 83:12-97:13 -/
def euclid_u8_loop (a : U8) (b : U8) : Result U8 :=
  if b != 0#u8
  then do
       let b1 ← a % b
       euclid_u8_loop b b1
  else ok a
partial_fixpoint

/- [gcd::euclid_u8]:
   Source: 'src/lib.rs', lines 70:8-103:9 -/
def euclid_u8 (a : U8) (b : U8) : Result U8 :=
  do
  let (a1, b1) ← if a > b
                   then ok (a, b)
                   else ok (b, a)
  let a2 ← euclid_u8_loop a1 b1
  if a2 = 0#u8
  then ok ()
  else do
       let i ← a % a2
       massert (i = 0#u8)
  if a2 = 0#u8
  then ok a2
  else do
       let i ← b % a2
       massert (i = 0#u8)
       ok a2

/- [gcd::{gcd::Gcd for u8}::gcd_binary]:
   Source: 'src/lib.rs', lines 112:12-114:13 -/
def GcdU8.gcd_binary (self : U8) (v : U8) : Result U8 :=
  binary_u8 self v

/- [gcd::{gcd::Gcd for u8}::gcd]:
   Source: 'src/lib.rs', lines 107:12-109:13 -/
def GcdU8.gcd (self : U8) (other : U8) : Result U8 :=
  GcdU8.gcd_binary self other

/- [gcd::{gcd::Gcd for u8}::gcd_euclid]:
   Source: 'src/lib.rs', lines 117:12-119:13 -/
def GcdU8.gcd_euclid (self : U8) (other : U8) : Result U8 :=
  euclid_u8 self other

/- Trait implementation: [gcd::{gcd::Gcd for u8}]
   Source: 'src/lib.rs', lines 105:8-120:9 -/
@[reducible]
def GcdU8 : Gcd U8 := {
  gcd := GcdU8.gcd
  gcd_binary := GcdU8.gcd_binary
  gcd_euclid := GcdU8.gcd_euclid
}

end gcd
